/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\models\rocket\rocketship.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useRef } from 'react'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'

const ROTATION_SPEED = 0.5;
export function Rocketship(props: any) {
  const { nodes, materials } = useGLTF('/models/rocket/rocketship.glb') as any
  const group = useRef<THREE.Group>(null);

  useFrame((state, delta) => {
    if (group.current) {
      group.current.rotation.y += delta * ROTATION_SPEED
    }
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Rocket_Ship_Circle003_1.geometry} material={materials.F44336} />
      <mesh geometry={nodes.Rocket_Ship_Circle003_1_1.geometry} material={materials.FFFFFF} />
      <mesh geometry={nodes.Rocket_Ship_Circle003_1_2.geometry} material={materials['455A64']} />
      <mesh geometry={nodes.Rocket_Ship_Circle003_1_3.geometry} material={materials['78909C']} />
      <mesh geometry={nodes.Rocket_Ship_Circle003_1_4.geometry} material={materials['80DEEA']} />
    </group>
  )
}

useGLTF.preload('/models/rocket/rocketship.glb')
