/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\models\star\star.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { ThreeElements } from '@react-three/fiber'

export function Star({ opacity, ...props }: { opacity: number } & ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/models/star/star.glb') as any
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Circle001_Circle007.geometry} material={materials.FF9800}>
        <meshStandardMaterial {...materials['lambert2SG.001']} opacity={opacity} transparent />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/star/star.glb')
